### PR TITLE
 Guard against exceeding Mollie's payment method maximum

### LINKED ISSUE #91: When amount to pay exceeds payment method max allowed amount the Order fails silently
Variable: The payment method limit. e.g., Credit Cards default to a 2k limit.

Scenario:
- Start and pay for a new subscription for a total charged amount that is less than the limit e.g. 100 euros.
- Adjust the subscription so that the total charged amount for the next cycle will be more than the allowed amount for the payment method. e.g., 2.5k on the credit card with a limit of 2k.
- Finish the billing cycle

What happens:
- Notice that when the billing cycle ends the order for 2.5k is created and an attempt is made to charge the CC.
- An error is returned from the Mollie API [for this call](https://github.com/mollie/laravel-cashier-mollie/blob/main/src/Order/Order.php#L230):
```
Error executing API call (422: Unprocessable Entity): The amount is higher than the maximum. Field: amount. Documentation: https://docs.mollie.com/overview/handling-errors
```
- This stops order processing in its tracks and does not throw any events which would make it possible to identify the failed payment. Next to that, the order stays marked with a temporary payment ID e.g., `temp_b2eeb17a-d886-235b-b4da-217dff33ecbd`

How should this case be handled?

### PR DESCRIPTION
**Pull request by ciungulete**

### CODE REVIEW

**Comment by sandervanhooft** [comment]
Hi @ciungulete !

Is this still WIP, as the title says?

**Comment by sandervanhooft** [comment]
Solves https://github.com/mollie/laravel-cashier-mollie/issues/91

File: src/Order/Order.php [hunk 1]
```diff
@@ -684,6 +696,24 @@ private function ensureValidMandateAndMinimumPaymentAmountWhenTotalDuePositive()
...
+     * @return \Money\Money
+     * @throws InvalidMandateException
+     */
+    private function ensureValidMandateAndMaximumPaymentAmountWhenTotalDuePositive(): \Money\Money
+    {
+        if ((int) $this->getTotalDue()->getAmount() > 0) {
+            $mandate = $this->owner->mollieMandate();
+            $this->guardMandate($mandate);
+
+            $maximumPaymentAnount = app(MaximumPayment::class)::forMollieMandate($mandate, $this->getCurrency());
```
Comment (sandervanhooft) [inline src/Order/Order.php:709]: typo

**Review by sandervanhooft — CHANGES_REQUESTED** [review]
Minor change. Nice!
